# Generated by Django 6.0.6 on 2026-06-17 00:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cuarto', models.CharField(default='principal', max_length=100)),
                ('voltaje_rms', models.FloatField()),
                ('corriente_rms', models.FloatField()),
                ('angulo_fase', models.FloatField()),
                ('potencia_activa', models.FloatField()),
                ('potencia_reactiva', models.FloatField()),
                ('potencia_aparente', models.FloatField()),
                ('factor_potencia', models.FloatField()),
                ('kwh_acumulado', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionGasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
                ('kwh_proyectado', models.FloatField()),
                ('costo_proyectado_soles', models.FloatField()),
                ('tarifa_usada', models.FloatField(default=0.6)),
            ],
            options={
                'verbose_name': 'Predicción de Gasto',
                'verbose_name_plural': 'Predicciones de Gasto',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='SesionDemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('total_kwh', models.FloatField(default=0.0)),
                ('artefactos_detectados', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Sesión Demo',
                'verbose_name_plural': 'Sesiones Demo',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='ArtefactoDetectado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_artefacto', models.CharField(max_length=100)),
                ('confianza', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefactos', to='mediciones.medicion')),
            ],
            options={
                'verbose_name': 'Artefacto Detectado',
                'verbose_name_plural': 'Artefactos Detectados',
                'ordering': ['-timestamp'],
            },
        ),
    ]
